version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo

  docker-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo

jobs:
  build-and-test:
    executor: java-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-{{ checksum "pom.xml" }}
      - run:
          name: Build and Test
          command: mvn clean verify
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/*.jar

  docker-build-local:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Local Docker Image
          command: |
            docker build -t ebanking-transactions-api:local .

workflows:
  version: 2
  build-test-local-docker:
    jobs:
      - build-and-test
      - docker-build-local:
          requires:
            - build-and-test
